<a href="https://colab.research.google.com/github/ayu69hub/Pyton-basic--adv/blob/main/libraries.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy**

In [ ]:
import numpy as np
a = np.arange(1, 10)
print(a)

[1 2 3 4 5 6 7 8 9]

In [ ]:
lst = [1,2,3,4,5]
arr = np.array(lst)
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>

In [ ]:
p = np.zeros((2,2))
q = np.ones((2,2))
print(p)
print(q)

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]

In [ ]:
lst1 = [1,2,3,4]
lst2 = [5,6,7,8]
lst3 = [9,10,11,12]

print(np.array([lst1, lst2, lst3]))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

In [ ]:
c = np.linspace(1, 11, 5)
print(c)

[ 1.   3.5  6.   8.5 11. ]

In [ ]:
a[2]=22
print(a)

[ 1  2 22  4  5  6  7  8  9]

In [ ]:
print(a[::-1])
print(a[:5:2])
print(a[:-1])

[ 9  8  7  6  5  4 22  2  1]
[ 1 22  5]
[ 1  2 22  4  5  6  7  8]

In [ ]:
arr1 = np.array([[1,2,3,4],
                 [2,3,4,5],
                 [3,4,5,6]])
print(arr1[:,1])
print(arr1[:2,1:3])

[2 3 4]
[[2 3]
 [3 4]]

In [ ]:
arr1.shape

(3, 4)

In [ ]:
arr1.reshape(4,3)

array([[1, 2, 3],
       [4, 2, 3],
       [4, 5, 3],
       [4, 5, 6]])

In [ ]:
np.random.rand(3,3)

array([[0.83119435, 0.23789751, 0.15301688],
       [0.14401681, 0.97520533, 0.15483848],
       [0.03650965, 0.36627752, 0.87771198]])

In [ ]:
np.random.randint(10,50,4)

array([40, 22, 11, 41])

In [ ]:
np.random.randn()

-1.227123691025229

In [ ]:
np.random.random_sample()

0.9571109383581988

# **Pandas**

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
np.arange(0,20).reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
df = pd.DataFrame(np.arange(0,20).reshape(5,4),index=["Row1","Row2","Row3","Row4","Row5"],columns=["Column1","Column2","Column3","Column4"])

In [ ]:
df.head()

      Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [ ]:
df.tail()

      Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [ ]:
df.isnull().count()

Column1    5
Column2    5
Column3    5
Column4    5
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, Row1 to Row5
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Column1  5 non-null      int64
 1   Column2  5 non-null      int64
 2   Column3  5 non-null      int64
 3   Column4  5 non-null      int64
dtypes: int64(4)
memory usage: 372.0+ bytes

In [ ]:
df.describe()

         Column1    Column2    Column3    Column4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

In [ ]:
df[["Column1","Column2","Column3"]]

      Column1  Column2  Column3
Row1        0        1        2
Row2        4        5        6
Row3        8        9       10
Row4       12       13       14
Row5       16       17       18

In [ ]:
df.loc["Row1"]

Column1    0
Column2    1
Column3    2
Column4    3
Name: Row1, dtype: int64

In [ ]:
df.loc[["Row1","Row3"]]

      Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row3        8        9       10       11

In [ ]:
df.loc[["Row1","Row3"]]

      Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row3        8        9       10       11

In [ ]:
df.iloc[2:4,0:2]

      Column1  Column2
Row3        8        9
Row4       12       13

In [ ]:
df.iloc[2:,1:]

      Column2  Column3  Column4
Row3        9       10       11
Row4       13       14       15
Row5       17       18       19

In [ ]:
df.iloc[:,:1]

      Column1
Row1        0
Row2        4
Row3        8
Row4       12
Row5       16

In [ ]:
df.iloc[:,3:]

      Column4
Row1        3
Row2        7
Row3       11
Row4       15
Row5       19

In [ ]:
#convert dataframe into arrays
df.iloc[:,1:].values

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

**#operations**

In [ ]:

df.isnull().sum()

Column1    0
Column2    0
Column3    0
Column4    0
dtype: int64

In [ ]:
df["Column2"].value_counts()

Column2
1     1
5     1
9     1
13    1
17    1
Name: count, dtype: int64

In [ ]:
df["Column3"].unique()

array([ 2,  6, 10, 14, 18])

In [ ]:
df>2

      Column1  Column2  Column3  Column4
Row1    False    False    False     True
Row2     True     True     True     True
Row3     True     True     True     True
Row4     True     True     True     True
Row5     True     True     True     True

In [ ]:
#stringIO se kisi bhi data ko string me convert kr skte h

In [ ]:
data = '{"employee_name": "James", "email": "james@gmail.com", "job_profile": [{"title1":"Team Lead", "title2":"Sr. Developer"}]}'
print(type(data))

<class 'str'>

In [ ]:
pd.read_json(data)

/tmp/ipykernel_15799/1661395064.py:1: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  pd.read_json(data)

,employee_name,email,job_profile
0,James,james@gmail.com,"{'title1': 'Team Lead', 'title2': 'Sr. Develop..."

In [ ]:
pd.read_json(data,orient="records")

/tmp/ipykernel_15799/4148957593.py:1: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  pd.read_json(data,orient="records")

,employee_name,email,job_profile
0,James,james@gmail.com,"{'title1': 'Team Lead', 'title2': 'Sr. Develop..."

In [ ]:
pd.read_json(data,orient="columns")

/tmp/ipykernel_15799/4169254557.py:1: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  pd.read_json(data,orient="columns")

,employee_name,email,job_profile
0,James,james@gmail.com,"{'title1': 'Team Lead', 'title2': 'Sr. Develop..."

In [ ]:
df = pd.DataFrame([['a', 'b'], ['c', 'd']],
                  index=['row 1', 'row 2'],
                  columns=['col 1', 'col 2'])
df

      col 1 col 2
row 1     a     b
row 2     c     d

In [ ]:
df.to_json()

'{"col 1":{"row 1":"a","row 2":"c"},"col 2":{"row 1":"b","row 2":"d"}}'

In [ ]:
df.to_json(orient="columns")

'{"col 1":{"row 1":"a","row 2":"c"},"col 2":{"row 1":"b","row 2":"d"}}'

In [ ]:
df.to_json(orient="index")

'{"row 1":{"col 1":"a","col 2":"b"},"row 2":{"col 1":"c","col 2":"d"}}'

In [ ]:
df.to_json(orient="split")

'{"columns":["col 1","col 2"],"index":["row 1","row 2"],"data":[["a","b"],["c","d"]]}'

In [ ]:
df.to_json(orient="table")

'{"schema":{"fields":[{"name":"index","type":"string"},{"name":"col 1","type":"string"},{"name":"col 2","type":"string"}],"primaryKey":["index"],"pandas_version":"1.4.0"},"data":[{"index":"row 1","col 1":"a","col 2":"b"},{"index":"row 2","col 1":"c","col 2":"d"}]}'

In [ ]:
data = [{"employee_name": "James", "email": "james@gmail.com", "job_profile": {"title1":"Team Lead", "title2":"Sr. Developer"}}]

In [ ]:

type(data)

list

In [ ]:

pd.json_normalize(data)

  employee_name            email job_profile.title1 job_profile.title2
0         James  james@gmail.com          Team Lead      Sr. Developer

In [ ]:
data = [
    {
        "state": "Florida",
        "shortname": "FL",
        "info": {"governor": "Rick Scott"},
        "counties": [
            {"name": "Dade", "population": 12345},
            {"name": "Broward", "population": 40000},
            {"name": "Palm Beach", "population": 60000},
        ],
    },
    {
        "state": "Ohio",
        "shortname": "OH",
        "info": {"governor": "John Kasich"},
        "counties": [
            {"name": "Summit", "population": 1234},
            {"name": "Cuyahoga", "population": 1337},
        ],
    },
]

In [ ]:
pd.json_normalize(data)

,state,shortname,counties,info.governor
0,Florida,FL,"[{'name': 'Dade', 'population': 12345}, {'name...",Rick Scott
1,Ohio,OH,"[{'name': 'Summit', 'population': 1234}, {'nam...",John Kasich

In [ ]:
pd.json_normalize(data, "counties",["state", "shortname",["info",'governor']])

         name  population    state shortname info.governor
0        Dade       12345  Florida        FL    Rick Scott
1     Broward       40000  Florida        FL    Rick Scott
2  Palm Beach       60000  Florida        FL    Rick Scott
3      Summit        1234     Ohio        OH   John Kasich
4    Cuyahoga        1337     Ohio        OH   John Kasich

**#Working with html**

In [ ]:
html = pd.read_html("https://www.fdic.gov/resources/resolutions/bank-failures/failed-bank-list/")

In [ ]:
type(html)

list

In [ ]:
html[0]

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,Community Bank and Trust - West Georgia,LaGrange,Georgia,25796,Anchor Bank,"May 1, 2026",10551
1,Metropolitan Capital Bank & Trust,Chicago,Illinois,57488,First Independence Bank,"January 30, 2026",10550
2,The Santa Anna National Bank,Santa Anna,Texas,5520,Coleman County State Bank,"June 27, 2025",10549
3,Pulaski Savings Bank,Chicago,Illinois,28611,Millennium Bank,"January 17, 2025",10548
4,The First National Bank of Lindsay,Lindsay,Oklahoma,4134,First Bank & Trust Co.,"October 18, 2024",10547
5,Republic First Bank dba Republic Bank,Philadelphia,Pennsylvania,27332,"Fulton Bank, National Association","April 26, 2024",10546
6,Citizens Bank,Sac City,Iowa,8758,Iowa Trust & Savings Bank,"November 3, 2023",10545
7,Heartland Tri-State Bank,Elkhart,Kansas,25851,"Dream First Bank, N.A.","July 28, 2023",10544
8,First Republic Bank,San Francisco,California,59017,"JPMorgan Chase Bank, N.A.","May 1, 2023",10543
9,Signature Bank,New York,New York,57053,"Flagstar Bank, N.A.","March 12, 2023",10540
10,Silicon Valley Bank,Santa Clara,California,24735,First–Citizens Bank & Trust Company,"March 10, 2023",10539
11,Almena State Bank,Almena,Kansas,15426,Equity Bank,"October 23, 2020",10538
12,First City Bank of Florida,Fort Walton Beach,Florida,16748,"United Fidelity Bank, fsb","October 16, 2020",10537
13,The First State Bank,Barboursville,West Virginia,14361,"MVB Bank, Inc.","April 3, 2020",10536
14,Ericson State Bank,Ericson,Nebraska,18265,Farmers and Merchants Bank,"February 14, 2020",10535
15,City National Bank of New Jersey,Newark,New Jersey,21111,Industrial Bank,"November 1, 2019",10534
16,Resolute Bank,Maumee,Ohio,58317,Buckeye State Bank,"October 25, 2019",10533
17,Louisa Community Bank,Louisa,Kentucky,58112,Kentucky Farmers Bank Corporation,"October 25, 2019",10532
18,The Enloe State Bank,Cooper,Texas,10716,"Legend Bank, N. A.","May 31, 2019",10531
19,Washington Federal Bank for Savings,Chicago,Illinois,30570,Royal Savings Bank,"December 15, 2017",10530
20,The Farmers and Merchants State Bank of Argonia,Argonia,Kansas,17719,Conway Bank,"October 13, 2017",10529
21,Fayette County Bank,Saint Elmo,Illinois,1802,"United Fidelity Bank, fsb","May 26, 2017",10528
22,"Guaranty Bank, (d/b/a BestBank in Georgia & Mi...",Milwaukee,Wisconsin,30003,First-Citizens Bank & Trust Company,"May 5, 2017",10527
23,First NBC Bank,New Orleans,Louisiana,58302,Whitney Bank,"April 28, 2017",10526
24,Proficio Bank,Cottonwood Heights,Utah,35495,Cache Valley Bank,"March 3, 2017",10525

What is XML?

XML stands for eXtensible Markup Language
XML is a markup language much like HTML
XML was designed to store and transport data
XML was designed to be self-descriptive
XML is a W3C Recommendation

In [ ]:
xml = '''<?xml version='1.0' encoding='utf-8'?>
<data xmlns="http://example.com">
 <row>
   <shape>square</shape>
   <degrees>360</degrees>
   <sides>4.0</sides>
   <firstname>Krish</firstname>
 </row>
 <row>
   <shape>circle</shape>
   <degrees>360</degrees>
   <sides/>
   <firstname/>
 </row>
 <row>
   <shape>triangle</shape>
   <degrees>180</degrees>
   <sides>3.0</sides>
   <firstname/>
 </row>
</data>'''

In [ ]:
pd.read_xml(xml)

/tmp/ipykernel_15799/2704978085.py:1: FutureWarning: Passing literal xml to 'read_xml' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  pd.read_xml(xml)

      shape  degrees  sides firstname
0    square      360    4.0     Krish
1    circle      360    NaN      None
2  triangle      180    3.0      None

In [ ]:
xml = '''<?xml version='1.0' encoding='utf-8'?>
<data>
  <row shape="square" degrees="360" sides="4.0" firstname="Krish"/>
  <row shape="circle" degrees="360"/>
  <row shape="triangle" degrees="180" sides="3.0" lastname="Naik"/>
</data>'''

In [ ]:
pd.read_xml(xml,xpath=".//row")

/tmp/ipykernel_15799/2888431730.py:1: FutureWarning: Passing literal xml to 'read_xml' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  pd.read_xml(xml,xpath=".//row")

      shape  degrees  sides firstname lastname
0    square      360    4.0     Krish     None
1    circle      360    NaN      None     None
2  triangle      180    3.0      None     Naik

In [ ]:
xml = '''<?xml version='1.0' encoding='utf-8'?>
<doc:data xmlns:doc="https://example.com">
  <doc:row>
    <doc:shape>square</doc:shape>
    <doc:degrees>360</doc:degrees>
    <doc:sides>4.0</doc:sides>
  </doc:row>
  <doc:row>
    <doc:shape>circle</doc:shape>
    <doc:degrees>360</doc:degrees>
    <doc:sides/>
  </doc:row>
  <doc:row>
    <doc:shape>triangle</doc:shape>
    <doc:degrees>180</doc:degrees>
    <doc:sides>3.0</doc:sides>
  </doc:row>
</doc:data>'''

In [ ]:
df=pd.read_xml(xml,xpath=".//doc:row",namespaces={"doc": "https://example.com"})

/tmp/ipykernel_15799/1616642587.py:1: FutureWarning: Passing literal xml to 'read_xml' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df=pd.read_xml(xml,xpath=".//doc:row",namespaces={"doc": "https://example.com"})

In [ ]:
df.to_xml('test1.xml')

**Pickling(seaborn)**

In [ ]:
import seaborn as sns

In [ ]:
df=sns.load_dataset('tips')

In [ ]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
import pickle

In [ ]:
filename='file.pkl'

In [ ]:
##serialize process
pickle.dump(df,open(filename,'wb'))

In [ ]:
##unsereliaze
df=pickle.load(open(filename,'rb'))

In [ ]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
dic_example={'first_name':'Krish','last_name':'Naik'}

In [ ]:
pickle.dump(dic_example,open('test.pkl','wb'))

In [ ]:
pickle.load(open('test.pkl','rb'))

{'first_name': 'Krish', 'last_name': 'Naik'}